'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = {
  code: string;
  name: string;
};

type Translations = {
  [key: string]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  en: {
    // Navbar
    signIn: 'Sign in',
    // Hero
    shareMarket: 'Share market',
    thoughts: 'thoughts.',
    discover: 'Discover',
    signal: 'signal.',
    subheadline: 'A social feed for stocks, ETFs, and crypto. Discover discussions through tickers and news. Explore AI experiments in Labs.',
    ideas: 'Ideas',
    assets: 'Assets',
    labs: 'Labs',
    notBrokerage: 'Not a brokerage',
    stocksEtfCrypto: 'Stocks • ETFs • Crypto',
    labsAi: 'Labs: AI Experiments',
    joinWaitlist: 'Join waitlist',
    // Auth Card
    joinPageShare: 'Join PageShare',
    authSubtitle: 'Share market thoughts. Discover discussions. Explore Labs.',
    signUpGoogle: 'Sign up with Google',
    signUpApple: 'Sign up with Apple',
    or: 'or',
    createAccount: 'Create account',
    termsText: 'By signing up, you agree to the',
    termsOfService: 'Terms of Service',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    including: 'including',
    cookieUse: 'Cookie Use',
    alreadyHaveAccount: 'Already have an account?',
    // Footer
    about: 'About',
    helpCenter: 'Help Center',
    cookiePolicy: 'Cookie Policy',
    accessibility: 'Accessibility',
    disclaimer: 'Disclaimer',
    blog: 'Blog',
    careers: 'Careers',
    brandResources: 'Brand Resources',
    api: 'API',
    contact: 'Contact',
    copyright: '© 2025 PageShare. Educational purposes only. Markets involve risk.',
  },
  es: {
    signIn: 'Iniciar sesión',
    shareMarket: 'Comparte mercado',
    thoughts: 'pensamientos.',
    discover: 'Descubre',
    signal: 'señal.',
    subheadline: 'Un feed social para acciones, ETF y cripto. Descubre discusiones a través de tickers y noticias. Explora experimentos de IA en Labs.',
    ideas: 'Ideas',
    assets: 'Activos',
    labs: 'Labs',
    notBrokerage: 'No es un bróker',
    stocksEtfCrypto: 'Acciones • ETF • Cripto',
    labsAi: 'Labs: Experimentos IA',
    joinWaitlist: 'Únete a la lista',
    joinPageShare: 'Únete a PageShare',
    authSubtitle: 'Comparte pensamientos de mercado. Descubre discusiones. Explora Labs.',
    signUpGoogle: 'Regístrate con Google',
    signUpApple: 'Regístrate con Apple',
    or: 'o',
    createAccount: 'Crear cuenta',
    termsText: 'Al registrarte, aceptas los',
    termsOfService: 'Términos de Servicio',
    and: 'y',
    privacyPolicy: 'Política de Privacidad',
    including: 'incluyendo',
    cookieUse: 'Uso de Cookies',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    about: 'Acerca de',
    helpCenter: 'Centro de Ayuda',
    cookiePolicy: 'Política de Cookies',
    accessibility: 'Accesibilidad',
    disclaimer: 'Descargo de responsabilidad',
    blog: 'Blog',
    careers: 'Carreras',
    brandResources: 'Recursos de Marca',
    api: 'API',
    contact: 'Contacto',
    copyright: '© 2025 PageShare. Solo para fines educativos. Los mercados implican riesgo.',
  },
  fr: {
    signIn: 'Se connecter',
    shareMarket: 'Partagez marché',
    thoughts: 'pensées.',
    discover: 'Découvrez',
    signal: 'signal.',
    subheadline: 'Un flux social pour actions, ETF et crypto. Découvrez des discussions via des tickers et actualités. Explorez des expériences IA dans Labs.',
    ideas: 'Idées',
    assets: 'Actifs',
    labs: 'Labs',
    notBrokerage: 'Pas un courtier',
    stocksEtfCrypto: 'Actions • ETF • Crypto',
    labsAi: 'Labs: Expériences IA',
    joinWaitlist: 'Rejoindre la liste',
    joinPageShare: 'Rejoignez PageShare',
    authSubtitle: 'Partagez des pensées de marché. Découvrez des discussions. Explorez Labs.',
    signUpGoogle: 'S\'inscrire avec Google',
    signUpApple: 'S\'inscrire avec Apple',
    or: 'ou',
    createAccount: 'Créer un compte',
    termsText: 'En vous inscrivant, vous acceptez les',
    termsOfService: 'Conditions de Service',
    and: 'et',
    privacyPolicy: 'Politique de Confidentialité',
    including: 'y compris',
    cookieUse: 'Utilisation des Cookies',
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    about: 'À propos',
    helpCenter: 'Centre d\'aide',
    cookiePolicy: 'Politique des Cookies',
    accessibility: 'Accessibilité',
    disclaimer: 'Avertissement',
    blog: 'Blog',
    careers: 'Carrières',
    brandResources: 'Ressources de Marque',
    api: 'API',
    contact: 'Contact',
    copyright: '© 2025 PageShare. À des fins éducatives uniquement. Les marchés comportent des risques.',
  },
  de: {
    signIn: 'Anmelden',
    shareMarket: 'Markt teilen',
    thoughts: 'Gedanken.',
    discover: 'Entdecken',
    signal: 'Signal.',
    subheadline: 'Ein sozialer Feed für Aktien, ETFs und Krypto. Entdecken Sie Diskussionen über Ticker und Nachrichten. Erkunden Sie KI-Experimente in Labs.',
    ideas: 'Ideen',
    assets: 'Vermögenswerte',
    labs: 'Labs',
    notBrokerage: 'Kein Broker',
    stocksEtfCrypto: 'Aktien • ETFs • Krypto',
    labsAi: 'Labs: KI-Experimente',
    joinWaitlist: 'Warteliste beitreten',
    joinPageShare: 'PageShare beitreten',
    authSubtitle: 'Marktgedanken teilen. Diskussionen entdecken. Labs erkunden.',
    signUpGoogle: 'Mit Google anmelden',
    signUpApple: 'Mit Apple anmelden',
    or: 'oder',
    createAccount: 'Konto erstellen',
    termsText: 'Mit der Anmeldung stimmen Sie den',
    termsOfService: 'Nutzungsbedingungen',
    and: 'und',
    privacyPolicy: 'Datenschutzrichtlinie',
    including: 'einschließlich',
    cookieUse: 'Cookie-Verwendung',
    alreadyHaveAccount: 'Haben Sie bereits ein Konto?',
    about: 'Über',
    helpCenter: 'Hilfezentrum',
    cookiePolicy: 'Cookie-Richtlinie',
    accessibility: 'Barrierefreiheit',
    disclaimer: 'Haftungsausschluss',
    blog: 'Blog',
    careers: 'Karrieren',
    brandResources: 'Markenressourcen',
    api: 'API',
    contact: 'Kontakt',
    copyright: '© 2025 PageShare. Nur zu Bildungszwecken. Märkte bergen Risiken.',
  },
  zh: {
    signIn: '登录',
    shareMarket: '分享市场',
    thoughts: '想法。',
    discover: '发现',
    signal: '信号。',
    subheadline: '股票、ETF和加密货币的社交信息流。通过代码和新闻发现讨论。在Labs中探索AI实验。',
    ideas: '想法',
    assets: '资产',
    labs: '实验室',
    notBrokerage: '不是经纪商',
    stocksEtfCrypto: '股票 • ETF • 加密货币',
    labsAi: '实验室：AI实验',
    joinWaitlist: '加入候补名单',
    joinPageShare: '加入PageShare',
    authSubtitle: '分享市场想法。发现讨论。探索实验室。',
    signUpGoogle: '使用Google注册',
    signUpApple: '使用Apple注册',
    or: '或',
    createAccount: '创建账户',
    termsText: '注册即表示您同意',
    termsOfService: '服务条款',
    and: '和',
    privacyPolicy: '隐私政策',
    including: '包括',
    cookieUse: 'Cookie使用',
    alreadyHaveAccount: '已有账户？',
    about: '关于',
    helpCenter: '帮助中心',
    cookiePolicy: 'Cookie政策',
    accessibility: '可访问性',
    disclaimer: '免责声明',
    blog: '博客',
    careers: '职业',
    brandResources: '品牌资源',
    api: 'API',
    contact: '联系',
    copyright: '© 2025 PageShare。仅用于教育目的。市场涉及风险。',
  },
  ja: {
    signIn: 'サインイン',
    shareMarket: '市場を共有',
    thoughts: '思考。',
    discover: '発見',
    signal: 'シグナル。',
    subheadline: '株式、ETF、暗号通貨のソーシャルフィード。ティッカーとニュースを通じてディスカッションを発見。LabsでAI実験を探索。',
    ideas: 'アイデア',
    assets: '資産',
    labs: 'ラボ',
    notBrokerage: 'ブローカーではありません',
    stocksEtfCrypto: '株式 • ETF • 暗号通貨',
    labsAi: 'ラボ：AI実験',
    joinWaitlist: 'ウェイトリストに参加',
    joinPageShare: 'PageShareに参加',
    authSubtitle: '市場の思考を共有。ディスカッションを発見。ラボを探索。',
    signUpGoogle: 'Googleでサインアップ',
    signUpApple: 'Appleでサインアップ',
    or: 'または',
    createAccount: 'アカウント作成',
    termsText: 'サインアップすることで、',
    termsOfService: '利用規約',
    and: 'および',
    privacyPolicy: 'プライバシーポリシー',
    including: '含む',
    cookieUse: 'Cookieの使用',
    alreadyHaveAccount: 'すでにアカウントをお持ちですか？',
    about: 'について',
    helpCenter: 'ヘルプセンター',
    cookiePolicy: 'Cookieポリシー',
    accessibility: 'アクセシビリティ',
    disclaimer: '免責事項',
    blog: 'ブログ',
    careers: 'キャリア',
    brandResources: 'ブランドリソース',
    api: 'API',
    contact: 'お問い合わせ',
    copyright: '© 2025 PageShare。教育目的のみ。市場にはリスクがあります。',
  },
  ko: {
    signIn: '로그인',
    shareMarket: '시장 공유',
    thoughts: '생각.',
    discover: '발견',
    signal: '신호.',
    subheadline: '주식, ETF 및 암호화폐를 위한 소셜 피드. 티커 및 뉴스를 통해 토론을 발견하세요. Labs에서 AI 실험을 탐색하세요.',
    ideas: '아이디어',
    assets: '자산',
    labs: '랩',
    notBrokerage: '브로커 아님',
    stocksEtfCrypto: '주식 • ETF • 암호화폐',
    labsAi: '랩: AI 실험',
    joinWaitlist: '대기 목록 가입',
    joinPageShare: 'PageShare 가입',
    authSubtitle: '시장 생각 공유. 토론 발견. 랩 탐색.',
    signUpGoogle: 'Google로 가입',
    signUpApple: 'Apple로 가입',
    or: '또는',
    createAccount: '계정 만들기',
    termsText: '가입하면 다음에 동의하는 것입니다',
    termsOfService: '서비스 약관',
    and: '및',
    privacyPolicy: '개인정보 보호정책',
    including: '포함',
    cookieUse: '쿠키 사용',
    alreadyHaveAccount: '이미 계정이 있으신가요?',
    about: '소개',
    helpCenter: '고객센터',
    cookiePolicy: '쿠키 정책',
    accessibility: '접근성',
    disclaimer: '면책 조항',
    blog: '블로그',
    careers: '채용',
    brandResources: '브랜드 리소스',
    api: 'API',
    contact: '연락처',
    copyright: '© 2025 PageShare. 교육 목적으로만 사용됩니다. 시장에는 위험이 따릅니다.',
  },
  pt: {
    signIn: 'Entrar',
    shareMarket: 'Compartilhe mercado',
    thoughts: 'pensamentos.',
    discover: 'Descubra',
    signal: 'sinal.',
    subheadline: 'Um feed social para ações, ETFs e cripto. Descubra discussões através de tickers e notícias. Explore experimentos de IA no Labs.',
    ideas: 'Ideias',
    assets: 'Ativos',
    labs: 'Labs',
    notBrokerage: 'Não é uma corretora',
    stocksEtfCrypto: 'Ações • ETFs • Cripto',
    labsAi: 'Labs: Experimentos IA',
    joinWaitlist: 'Entrar na lista',
    joinPageShare: 'Junte-se ao PageShare',
    authSubtitle: 'Compartilhe pensamentos de mercado. Descubra discussões. Explore Labs.',
    signUpGoogle: 'Inscrever-se com Google',
    signUpApple: 'Inscrever-se com Apple',
    or: 'ou',
    createAccount: 'Criar conta',
    termsText: 'Ao se inscrever, você concorda com os',
    termsOfService: 'Termos de Serviço',
    and: 'e',
    privacyPolicy: 'Política de Privacidade',
    including: 'incluindo',
    cookieUse: 'Uso de Cookies',
    alreadyHaveAccount: 'Já tem uma conta?',
    about: 'Sobre',
    helpCenter: 'Central de Ajuda',
    cookiePolicy: 'Política de Cookies',
    accessibility: 'Acessibilidade',
    disclaimer: 'Aviso Legal',
    blog: 'Blog',
    careers: 'Carreiras',
    brandResources: 'Recursos da Marca',
    api: 'API',
    contact: 'Contato',
    copyright: '© 2025 PageShare. Apenas para fins educacionais. Os mercados envolvem riscos.',
  },
  ru: {
    signIn: 'Войти',
    shareMarket: 'Поделитесь рынком',
    thoughts: 'мыслями.',
    discover: 'Откройте',
    signal: 'сигнал.',
    subheadline: 'Социальная лента для акций, ETF и криптовалют. Откройте для себя обсуждения через тикеры и новости. Исследуйте эксперименты с ИИ в Labs.',
    ideas: 'Идеи',
    assets: 'Активы',
    labs: 'Лаборатории',
    notBrokerage: 'Не брокер',
    stocksEtfCrypto: 'Акции • ETF • Крипто',
    labsAi: 'Labs: Эксперименты ИИ',
    joinWaitlist: 'Присоединиться к списку',
    joinPageShare: 'Присоединиться к PageShare',
    authSubtitle: 'Поделитесь мыслями о рынке. Откройте обсуждения. Исследуйте Labs.',
    signUpGoogle: 'Зарегистрироваться через Google',
    signUpApple: 'Зарегистрироваться через Apple',
    or: 'или',
    createAccount: 'Создать аккаунт',
    termsText: 'Регистрируясь, вы соглашаетесь с',
    termsOfService: 'Условиями обслуживания',
    and: 'и',
    privacyPolicy: 'Политикой конфиденциальности',
    including: 'включая',
    cookieUse: 'Использование файлов cookie',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    about: 'О нас',
    helpCenter: 'Центр помощи',
    cookiePolicy: 'Политика файлов cookie',
    accessibility: 'Доступность',
    disclaimer: 'Отказ от ответственности',
    blog: 'Блог',
    careers: 'Карьера',
    brandResources: 'Ресурсы бренда',
    api: 'API',
    contact: 'Контакты',
    copyright: '© 2025 PageShare. Только в образовательных целях. Рынки сопряжены с рисками.',
  },
  ar: {
    signIn: 'تسجيل الدخول',
    shareMarket: 'شارك السوق',
    thoughts: 'أفكار.',
    discover: 'اكتشف',
    signal: 'إشارة.',
    subheadline: 'خلاصة اجتماعية للأسهم وصناديق الاستثمار المتداولة والعملات المشفرة. اكتشف المناقشات من خلال الرموز والأخبار. استكشف تجارب الذكاء الاصطناعي في Labs.',
    ideas: 'أفكار',
    assets: 'الأصول',
    labs: 'المختبرات',
    notBrokerage: 'ليس وسيط',
    stocksEtfCrypto: 'أسهم • صناديق • عملات مشفرة',
    labsAi: 'المختبرات: تجارب الذكاء الاصطناعي',
    joinWaitlist: 'انضم إلى القائمة',
    joinPageShare: 'انضم إلى PageShare',
    authSubtitle: 'شارك أفكار السوق. اكتشف المناقشات. استكشف المختبرات.',
    signUpGoogle: 'التسجيل عبر Google',
    signUpApple: 'التسجيل عبر Apple',
    or: 'أو',
    createAccount: 'إنشاء حساب',
    termsText: 'بالتسجيل، أنت توافق على',
    termsOfService: 'شروط الخدمة',
    and: 'و',
    privacyPolicy: 'سياسة الخصوصية',
    including: 'بما في ذلك',
    cookieUse: 'استخدام ملفات تعريف الارتباط',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
    about: 'حول',
    helpCenter: 'مركز المساعدة',
    cookiePolicy: 'سياسة ملفات تعريف الارتباط',
    accessibility: 'إمكانية الوصول',
    disclaimer: 'إخلاء المسؤولية',
    blog: 'المدونة',
    careers: 'الوظائف',
    brandResources: 'موارد العلامة التجارية',
    api: 'API',
    contact: 'اتصل',
    copyright: '© 2025 PageShare. للأغراض التعليمية فقط. الأسواق تنطوي على مخاطر.',
  },
};

const defaultLanguages: Language[] = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
  { code: 'zh', name: '中文' },
  { code: 'ja', name: '日本語' },
  { code: 'ko', name: '한국어' },
  { code: 'pt', name: 'Português' },
  { code: 'ru', name: 'Русский' },
  { code: 'ar', name: 'العربية' },
];

const LanguageContext = createContext<{
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
  languages: Language[];
}>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => translations['en'][key] || key,
  languages: defaultLanguages,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<string>('en');
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
    // Load saved language from localStorage
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('pageShare-language');
      if (savedLanguage && translations[savedLanguage]) {
        setLanguageState(savedLanguage);
      }
    }
  }, []);

  const setLanguage = (lang: string) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('pageShare-language', lang);
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  const languages: Language[] = [
    { code: 'en', name: 'English' },
    { code: 'es', name: 'Español' },
    { code: 'fr', name: 'Français' },
    { code: 'de', name: 'Deutsch' },
    { code: 'zh', name: '中文' },
    { code: 'ja', name: '日本語' },
    { code: 'ko', name: '한국어' },
    { code: 'pt', name: 'Português' },
    { code: 'ru', name: 'Русский' },
    { code: 'ar', name: 'العربية' },
  ];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

